### ISSUE TITLE
Audting spec

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#144]
Spec out what audting we should be doing and how to expose the data to users.

Look at the following projects:
* https://github.com/jazzband/django-auditlog
* https://github.com/dimagi/django-field-audit

**Comment by SmittieC** [comment]
The [spec](https://docs.google.com/document/d/11DS5j0jFjSBEvJxm35BRXZwajyJuivlLK62NqGlctsk/edit)

**Comment by SmittieC** [comment]
### Models to audit
- [ ] CustomUser
- [ ] Team
- [ ] Membership
- [ ] Experiment
- [ ] SourceMaterial
- [ ] SafetyLayer
- [ ] NoActivityMessageConfig
- [ ] ConsentForm
- [ ] LlmProvider
- [ ] VoiceProvider
- [ ] MessagingProvider
- [ ] ChannelPlatform
