### ISSUE TITLE
Prompt builder support for available models from the LLM Provider

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#163]
Write now the prompt builder is hardcoded with gpt-4 and 3.5 turbo. We should have it instead pull from the available models for a LLM provider for the current team. 

When we do that, we should probably move it back to the starting tab since it'll be important to show. Before the answer was always `gpt-4`, but probably the correct default now would be gpt-4 turbo. and there's at least one project that I think is going to try to use Anthropic/claude2.1.

(note the prompt builder is probably due for a larger overhaul, but I think we can put it off a bit longer)

**Comment by snopoke** [comment]
I'm pretty sure you can select the model. Here's a screenshot from the 'model properties' tab:



![Image](https://github.com/dimagi/open-chat-studio/assets/249606/a95cd355-9a9a-4c2e-93d9-2e144b87613d)

**Comment by bderenzi** [comment]
Yep. 

The issue is that it is hardcoded:
https://github.com/dimagi/open-chat-studio/blob/4346dd8030b9925ca712b52566ffbb513d0f16bc/templates/experiments/components/prompt_builder_toolbox.html#L52-L55

So, it didn't benefit when we added support for specifying specific models on LLM providers. There's no way to choose GPT-4-turbo for the prompt builder. 

The easy change I was trying to propose would be to:

- [ ] Rewrite the linked code to populate that select from the specific LLM provider models that are being proposed. This will need to be based on the LLM provider selected.
- [ ] (optional) Move the model selector (and LLM provider selector) to the first tab
