### ISSUE TITLE
Login and viewing transcripts

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#168]
To recreate:

1. Get a link for a transcript. In my testing I used a Telegram transcript, but shouldn't matter.
2. Log out of OCS.
3. You can still view the transcript even though you're not logged in. Expected behaviour: it should fail.

This doesn't happen in incognito mode, so it's something about having been logged in at some point? I don't know.

My first guess would be to add:
```
@permission_required("experiments.XXX", raise_exception=True)
```
(where XXX is the `ChatViewer` permission) as a decorator for:
https://github.com/dimagi/open-chat-studio/blob/4346dd8030b9925ca712b52566ffbb513d0f16bc/apps/experiments/views/experiment.py#L669

**Comment by snopoke** [comment]
This view actually needs to be accessible because it's shown to users at the end of a session. It handles the survey and then shows them the session review page.

**Comment by bderenzi** [comment]
Oh, that's a good point. That only applies to anonymous web sessions through the public link, right? If we're using Telegram we'd never see it. And if we're using web for logged in users only, we wouldn't have that problem.

I think we're going to need a feature to turn that off and make this view not-publicly-accessible for some of our IRB-approved research work.

**Comment by snopoke** [comment]
We could disable based on the channel ie. only enable for web channel. We could also use a cookie when a participant starts a chat and use to to permit review.
