### ISSUE TITLE
Multiple ways to mark person as administrator

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#23]
You can mark a person as a superuser under their user account. There is also an administrator role in the team. I believe we are only using the standard Django superuser flag to decide if we show the edit experiment button etc. We should resolve this and make it more clear.

Note, this is likely related to #24

**Comment by czue** [comment]
I think part of implementing #24 will be adding first class "edit experiment" views, at which point we should stop editing anything through the Django admin and move everything over to the tenant permission model
