### ISSUE TITLE
Context limit reached issue

### ISSUE THREAD

**Issue by SmittieC** [dimagi/open-chat-studio#25]
We've seen a few times now that the bot's context limits are being reached. This is due to either (or the combination of) the following
1. Long source material
2. Long user prompt
3. Long chat history

A possible solution that @bderenzi and I discussed is to look into LangChain's [Conversation Summary Buffer](https://python.langchain.com/docs/modules/memory/types/summary_buffer).

**Comment by snopoke** [comment]
Resolved by #206
