### ISSUE TITLE
Document environment variables on the wiki

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#28]
We need to document the environment variables we expect like `SIGNUP_ENABLED`. 

An incomplete list:

1. `SIGNUP_ENABLED` (Can be "True" or "False" to turn on/off sign-ups).
2. `OPENAI_API_KEY`
3. `MAILGUN_API_KEY` (for sending emails)
4. `ACCOUNT_EMAIL_VERIFICATION` (we set it to 'mandatory')
5. `DJANGO_SETTINGS_MODULE` (optional?)
6. `DATABASE_URL` (optional?)
7. `REDIS_URL` (optional?)
8. `SECRET_KEY`

For WhatsApp integration:

1. `TWILIO_ACCOUNT_SID`
2. `TWILIO_AUTH_TOKEN `

For AWS Polly integration:

1. `AWS_POLLY_ACCESS_KEY_ID`
2. `AWS_POLLY_SECRET_KEY`

**Comment by SmittieC** [comment]
I think we can close this out? Between the [Readme](https://github.com/dimagi/open-chat-studio/blob/main/app.json) and the [example .env](https://github.com/dimagi/open-chat-studio/blob/main/.env.example) file I think the important env variables are covered

**Comment by SmittieC** [comment]
Closing this
