### ISSUE TITLE
Remove default consent form

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#29]
We should probably remove the hardcoded default consent form since it reference's Dimagi names and contact details:

https://github.com/dimagi/open-chat-studio/blob/1c6de115cdea269126cb2346cf74e4d6e94569bb/templates/experiments/consent/consent_default.md

Having a default is still a good idea, but should probably be configured somewhere in the DB instead of in the repo.

**Comment by SmittieC** [comment]
The user can create their own form and override the default one for the experiment.
![image](https://github.com/dimagi/open-chat-studio/assets/64970009/a58fa1d1-47d6-4e16-b36c-cdd4f54193e7)

**Comment by SmittieC** [comment]
Oh I misunderstood the initial issue then. Coolios!
