### ISSUE TITLE
Upgrade langchain

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#362]
Why?
* Stay on a recent version
* New Anthropic messaging API
* Anthropic tool support

and more

**Comment by SmittieC** [comment]
Langchain is already updated and [here's](https://github.com/dimagi/open-chat-studio/pull/370) the anthropic tool support changes

**Comment by bderenzi** [comment]
Great! Do we need to make a separate issue for the anthropic messaging API? I think that's still not working (so no claude-3 on OCS at the moment)

**Comment by SmittieC** [comment]
The messaging API issue is fixed by us using the `ChatAnthoripic` model from langchain_anthropic now instead of the one from langchain_community. This reminds me, only the claude3 models supports tool usage
