### ISSUE TITLE
Validate channel inputs

### ISSUE THREAD

**Issue by SmittieC** [dimagi/open-chat-studio#367]
When linking a channel, we should validate the channel identifier inputs. For instance, whatsapp channels expect numbers, so we should normalize and validate it. This way, we can prevent users from linking two channels with the same number but different spacing.

**Comment by snopoke** [comment]
@SmittieC is there any more to do on this or can we close it?

**Comment by SmittieC** [comment]
If we want to validate facebook / slack inputs as well, then yes. Maybe not needed?

**Comment by snopoke** [comment]
> If we want to validate facebook / slack inputs as well, then yes. Maybe not needed?

We are already validating slack but fine to keep open for facebook.

**Comment by SmittieC** [comment]
I don't find a reliable way to verify a facebook page ID. There's [this handwavy method](https://stackoverflow.com/questions/17504486/how-to-check-if-a-facebook-id-is-valid), but I'm not sure how much I trust that in the longer term. I think until we have more people using this and starting to get issues, we can revisit. Closing this out for now
