### ISSUE TITLE
Add dates to the chat transcript messages view

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#421]
Use a [<time>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) element with a `title` attribute. The datetime should be rendered with timezone information displayed (ideally this would be in the user's timezone)

**Comment by SmittieC** [comment]
[django-tz-detect](https://pypi.org/project/django-tz-detect/) seems like it could be helpful here

**Comment by snopoke** [comment]
> [django-tz-detect](https://pypi.org/project/django-tz-detect/) seems like it could be helpful here

That does look potentially useful. We may also want to store the user's timezone in their profile.
