### ISSUE TITLE
Voice support for multi prompt

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#450]
For one project they are interested in having different voice responses for the multi-prompt endpoints. Right now voice response is only configured by the router prompt (I believe). The project wanted to use different endpoints for different characters, so they should have a unique voice.

**Comment by SmittieC** [comment]
Are they using the API? Your mention of "endpoints" lead me to think that they are

**Comment by bderenzi** [comment]
No, sorry. That's just the term they were using for the leaf nodes of the multi-prompt. As in the end of the chain or something

**Comment by bderenzi** [comment]
No, sorry. That's just the term they were using for the leaf nodes of the multi-prompt. As in the end of the chain or something
