### ISSUE TITLE
Ability to whitelist or blacklist participants for experiments

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#484]
For the research studies, it's important that only participants who have been recruited and consented into the study have access to the chatbot (and the research team). We need the ability to specify a set of participants that should be allowed to interact with the chatbot.

For failures, we should either fail silently or allow an optional static reply. (I could imagine a future where we want to use an LLM to generate a reply, but let's wait until there's a clear use case before doing that.)

**Comment by SmittieC** [comment]
So these experiments wouldn't be using consent forms?

**Comment by bderenzi** [comment]
They will use consent forms that are external to OCS. That is, it's not an open recruitment for anyone with the link / phone number.
