### ISSUE TITLE
File download from OpenAI is returning corrupt files

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#579]
When an OpenAI Assistant creates a file, we offer a download link to the user. Unfortunately, the contents of the file are corrupted. Viewing the same thread on the OpenAI site and downloading from there works correctly

See this slack thread for more details:
https://dimagi.slack.com/archives/C04VBQJ1DL3/p1722854203149329

**Comment by SmittieC** [comment]
https://github.com/dimagi/open-chat-studio/pull/582
