### ISSUE TITLE
Tool to update participant data

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#657]

**Comment by SmittieC** [comment]
What's the usecase here? Or what participant data do we want to update per se?

**Comment by snopoke** [comment]
The primary use case is to support deterministic routers in a multi-bot setup where we can use participant data to determine the routing.

**Comment by SmittieC** [comment]
Oh so things like preferred language etc?

**Comment by snopoke** [comment]
Yes, I think it will just be key value type updates. Things like language or 'tutorial_complete'.
