### ISSUE TITLE
Support Azure OpenAI

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#70]
https://azure.microsoft.com/en-us/products/ai-services/openai-service

**Comment by ishaan-jaff** [comment]
Hi @snopoke @SmittieC - I believe we can make this easier
I’m the maintainer of LiteLLM - we allow you to deploy a LLM proxy to call 100+ LLMs in 1 format - Azure OpenAI, PaLM, Bedrock, OpenAI, Anthropic etc https://github.com/BerriAI/litellm/tree/main/openai-proxy. 

If this looks useful (we're used in production)- please let me know how we can help.

## Usage 

Azure request
```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "azure/<your-deployment-name>",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

gpt-3.5-turbo request
```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

claude-2 request 
```shell
curl http://0.0.0.0:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
     "model": "claude-2",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

**Comment by snopoke** [comment]
Resolved by:
* https://github.com/dimagi/open-chat-studio/pull/72
* https://github.com/dimagi/open-chat-studio/pull/78
