### ISSUE TITLE
pipeline UX improvements

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#716]
### General
* Nodes should have some [help text](https://daisyui.com/components/dropdown/#helper-dropdown) giving more info about what they do
* ~~Move node list to dropdown. See https://flowiseai.com/~~

### Router

* Clicking the up / down arrow of the number of outputs input makes the value increase/ decrease indefinitely
* Output nodes should be numbered or named to make it easier to know which  is which

**Comment by SmittieC** [comment]
- Feedback to the user when the pipeline is saved

**Comment by snopoke** [comment]
@bderenzi FYI

**Comment by SmittieC** [comment]
> Output nodes should be numbered or named to make it easier to know which is which

@snopoke what is meant by this exactly?
