### ISSUE TITLE
Source Material showing in chat

### ISSUE THREAD

**Issue by stephherbers** [dimagi/open-chat-studio#840]
<img width="881" alt="Screenshot 2024-11-07 at 2 39 09 PM" src="https://github.com/user-attachments/assets/ed744b57-da86-431e-b923-ad5b602a8e31">

source material reference is shown. Instead the user should be unaware of the source material

**Comment by SmittieC** [comment]
This looks like an assistant based bot, in which case the source material is the file contents. The assistant is quoting from the file and referencing it. If this is undesired behaviour, the user can instruct the assistant in the prompt to never quote directly, but only give interpreted info. There's not much we can do from the server's side

**Comment by bderenzi** [comment]
Shouldn't they just turn off citations under advanced?

**Comment by stephherbers** [comment]
ah I didn't know that setting existed-- closing out

**Comment by SmittieC** [comment]
Oh is that the issue. I thought we mustn't show the raw contents of the source material. Anycase, what Brian said.
