### ISSUE TITLE
Support archiving experiments

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#873]
Right now the only way to remove an experiment from the list is to delete it. That's rather permanent. Can we instead archive it and have some way to look at archived projects?

**Comment by SmittieC** [comment]
Sounds good. Just to be sure I understand the context: I remember you saying that people generally don't delete their bots. Do you have a sense of why? I'm presuming one reason would be to reference it agan in the future, as you mentioned above. If that's the case, I can imagine a "favourites" list feature might come in handy :thinking: 

I'm going out on a limb here

**Comment by SmittieC** [comment]
This is done
