### ISSUE TITLE
Enable send button when there is an attachment

### ISSUE THREAD

**Issue by bderenzi** [dimagi/open-chat-studio#904]
Right now the send button on the web interface is disabled until we type something into the input box. This is good. We should also enable it if there's an attachment. I think we should be able to send a blank user message with the attachment and/or spoof something like "attachment"

**Comment by snopoke** [comment]
@bderenzi I tried this [here](https://github.com/dimagi/open-chat-studio/compare/sk/chat-attachment-tweaks?expand=1) but it didn't work very well.

With no input I got an error from OpenAI: `Message content must be non-empty.`. If I used a ' ' (space) for the message the Assistant replied `It seems like your message didn't come through. Could you please try sending it again?`

**Comment by bderenzi** [comment]
Interesting. I wonder if a better approach is to pre-fill the input box
with "attachment" if the input box is empty when the user adds an
attachment. that way they can see / edit it if necessary and hopefully
that's enough to kick off the prompt.

The alternative is to send that message without the user knowing. I.e., if
they attach and send when the input is empty we send "attachment" to
OpenAI. This feels somewhat better from a UX perspective, but a bit worse
because then we're sending input the user never gets a chance to see.

Also, it might be that something more complete like "Please look at the
attached file(s) and respond appropriately" would be better.
