### ISSUE TITLE
Investigate intermittent load errors

### ISSUE THREAD

**Issue by stephherbers** [dimagi/open-chat-studio#917]
flagged on slack thread [here](https://dimagi.slack.com/archives/C05PK63Q89H/p1732304614247809) 

this team is reporting these errors as “consistently”
initial investigation did not return any solid leads

**Comment by lmagoun** [comment]
Partner checked in - still doesn't work. Is there an update on how to move this forward?

**Comment by snopoke** [comment]
This appears to be due to rate limiting from OpenAI. The partner should check the status of their OpenAI account and the API key they are using.
