### ISSUE TITLE
Separate assistant's internal tools and enabling and file uploads

### ISSUE THREAD

**Issue by SmittieC** [dimagi/open-chat-studio#924]
We don't always want users to be uploading files when CI or FS is enabled for assistants. This should be configurable

**Comment by snopoke** [comment]
Should this be at the assistant level or at the experiment level.

At the assistant level it could be a global option or it could be per 'tool' (allow uploads for CI but not FS).

If it's at the assistant level (global or per tool) then it applies to all experiments / pipelines that the assistant is used in.

Alternatively it could be applied at the experiment level which would only apply to that experiment. 

Applying it at the assistant level is slightly easier.

In future if we allow attachments for non-assitant bots we'll need something at the experiment level too.
