### ISSUE TITLE
UI for creating reminders

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio#93]

**Comment by snopoke** [comment]
> This was introduced for a very specific use-case, so I just want to confirm that this is going to be an official platform feature?

OK sounds good, it's one of the last remaining things that the admin UI is needed for.

**Comment by SmittieC** [comment]
I reached out to Delta to get a feel for how this feature is used, so I'll write a small spec. Also, just referencing [this PR](https://github.com/dimagi/open-chat-studio/pull/157) for the sake of not losing it.

**Comment by SmittieC** [comment]
@snopoke feel free to close this ticket if it's going to be resolved (or dissolved) into the scheduling feature
